config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'manage/projects', to: 'manage#projects', as: :manage_projects

  root to: 'home#index'

  # Users go to site.url/request to create new projects
  get 'request', to: 'projects#new'
  post 'request', to: 'projects#create'

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get 'signup', to: 'devise/registrations#new', as: :new_user_registration
    post 'signup', to: 'devise/registrations#create', as: :user_registration
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :user_logout
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :project
end

app/models/format.rb
class Format < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 3 }

  has_many :formats, through: :project_format
  has_many :attachments

  @@status_names = ['Submitted', 'Started', 'Proofing', 'Ready']

  def status_name
    @@status_names[self.status]
  end
end

app/models/project_format.rb
class ProjectFormat < ApplicationRecord
  belongs_to :project
  has_one :format
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :group, optional: true
  has_many :projects

  def is_admin
    self.group && self.group.permissions == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  def projects
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(created_at: :desc)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash.notice = 'Project created. Bookmark this page to keep tabs on your project\'s progress.'
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def manage
    @projects = Project.all
  end

  private def project_params
    params.require(:project)
          .permit(:title,
                  :description,
                  :organization,
                  :location,
                  :when,
                  :due,
                  :status,
                  :contact_name,
                  :contact_email,
                  :contact_phone)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    # Override the action you want here.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manag_helper.rb
module ManagHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<p>
  Welcome to Bigfoot Marketing! We do graphic design and marketing for events organized by Bigfoot Events and SCC student organizations and clubs.
</p>

<% if !user_signed_in? %>
  <p>
    We use this site to keep track of graphics requests. Just <%= link_to 'create an account', new_user_registration_path %> with your email address and you'll be able to submit graphics requests, keep track of projects you've submitted and get notified when your materials are ready for pickup.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <meta name="viewport" content="min-width=1,width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navigation' %>

    <main>
      <ul class="messages-list">
        <% flash.each do |name, message| %>
          <li class="message message--<%= name %>">
            <span class="message-text"><%= message %></span>
            <a href="#" class="message-close">&times;</a>
          </li>
        <% end %>
      </ul>

      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header class="nav-header">
  <%= link_to root_path, class: 'nav-logo-link' do %>
    Bigfoot Marketing
  <% end %>
  <a href="#" class="mobile-nav-toggle"></a>
  <nav class="main-nav">
    <% if user_signed_in? %>
      <%= active_link_to 'Your Projects', projects_path %>
      <% if current_user.is_admin %>
        <%= active_link_to 'Manage Projects', manage_projects_path %>
      <% end %>
      <%= active_link_to 'Log Out', user_logout_path %>
    <% else %>
      <%= active_link_to 'Log In', new_user_session_path %>
    <% end %>
  </nav>
</header>

app/views/partials/_project.html.erb
<div class="project-card">
  <div class="project-card-header">
    <%= link_to project.title, project_path(project), class: 'project-card-title' %>
    <div class="project-card-status">
      <span class="project-card-status-text"><%= project.status_name %></span>
      <div class="project-card-status-bar">
        <div class="project-card-status-fill"
             <%= raw "style='width: #{(project.status + 1) * 25}%'" %>></div>
      </div>
    </div>
  </div>
  <div class="project-card-info">
    
  </div>
  <%= link_to 'Edit', edit_project_path(project) %>
</div>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= form_with(model: @project) do |form| %>
  <% if @project.errors.any? %>
    <div id="error-explanation">
      <h2>
        Fix these <%= pluralize(@project.errors.count, 'error') %>:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :when, 'Date' %><br>
    <%= form.text_field :when %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= link_to 'Create New Project', new_project_path %>

<% if @projects %>
  <div class="projects-list">
    <% @projects.each do |project| %>
      <div class="project-card">
        <div class="project-card-header">
          <%= link_to project.title, project_path(project), class: 'project-card-title' %>
          <div class="project-card-status">
            <span class="project-card-status-text"><%= project.status_name %></span>
            <div class="project-card-status-bar">
              <div class="project-card-status-fill"
                   <%= raw "style='width: #{(project.status + 1) * 25}%'" %>></div>
            </div>
          </div>
        </div>
        <div class="project-card-info">
          <div class="project-card-info-section">
            <span class="card-info-section-title"></span>
            <span class="card-info-label"><%= %></span> 
          </div>
        </div>
        <%= link_to 'Edit', edit_project_path(project) %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>
    You don't have any current projects.
  </p>
<% end %>

app/views/projects/new.html.erb
<%= form_with(scope: :project,
              local: true,
              url: projects_path,
              class: 'request-form') do |form| %>

  <% if @project.errors.any? %>
    <div id="error-explanation">
      <h2>
        Fix these <%= pluralize(@project.errors.count, 'error') %>:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-section">
    <header>
      <h2>Contact Info</h2>
    </header>

    <div class="form-split-group">
      <div class="form-set">
        <%= form.label :organization %>
        <%= form.text_field :organization %>
      </div>
      <div class="form-set">
        <%= form.label :contact_name %>
        <%= form.text_field :contact_name %>
      </div>
    </div>

    <div class="form-split-group">
      <div class="form-set">
        <%= form.label :contact_email %>
        <%= form.text_field :contact_email %>
      </div>

      <div class="form-set">
        <%= form.label :contact_phone %>
        <%= form.text_field :contact_phone %>
      </div>
    </div>
  </div>

  <div class="form-section">
    <input type="checkbox" id="event-checkbox"> This is for an event

    <div id="event-info">
      <header>
        <h2>Event Info</h2>
      </header>
      <div class="form-set">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </div>
      <div class="form-split-group">
        <div class="form-set">
          <%= form.label :location %>
          <%= form.text_field :location %>
        </div>
        <div class="form-set">
          <%= form.label :when, 'Event Date' %>
          <%= form.text_field :when %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-section">
    <header>
      <h2>Design</h2>
    </header>

    <div class="form-set">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="form-set">
      <%= form.label 'Attach files' %>
    </div>
  </div>

  <div class="form-section">
    <%= form.submit 'Submit', class: 'form-submit' %>
  </div>
  
<% end %>

<form class="dropzone" action="/project/<%= @project.id %>/files/upload"></form>

<%= link_to 'Back', projects_path %>

<script>
  var eventSection = document.getElementById('event-info');
  var checkbox = document.getElementById('event-checkbox');

  eventSection.classList.add('hidden');

  checkbox.addEventListener('click', function() {
    if (this.checked) {
      eventSection.classList.remove('hidden');
    } else {
      eventSection.classList.add('hidden');
    }
  });
</script>

app/views/projects/show.html.erb
<h1>Project View</h1>

<p>
  <strong>Title</strong><br>
  <%= @project.title %>
</p>

<p>
  <strong>Description</strong><br>
  <%= @project.description %>
</p>

<%= link_to 'Back to Projects', projects_path %>